apiVersion: v1
kind: ServiceAccount
metadata:
  name: podcreator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nomount-sa
automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
spec:
  containers:
    - image: nginx:latest
      name: nginxpod
  serviceAccountName: podcreator.yaml
  automountServiceAccountToken: false
